# Basic
title: Charles's Blog
subtitle: 悟以往之不谏，知来者之可追。
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 你好！我叫邱浩盛，是一位 iOS 开发者，现居深圳。
creator: <a href="https://github.com/charlesqiu">Charles.Qiu</a>

url: "https://charlesqiu.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: charlesqiu
    # duoshuo:

# Social
social:
    # weibo: onevcat
    github: charlesqiu
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: qhs@outlook.com

# Google Analytics
# ga:
    # id: your_ga_id
    # host: your_host
